# Book settings
title: Deep Learning Portfolio
author: Nicole S. Menorias
logo: logo.png   # optional, remove this line if you don’t have a logo

# Execution settings
execute:
  execute_notebooks: auto   # run only if needed (faster builds)

# Repository settings (links to GitHub)
repository:
  url: https://github.com/NicoleMenorias/deeplearning-portfolio
  branch: main
  path_to_book: .

# HTML settings
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
