# Book settings
title: Deep Learning Portfolio
author: Nicole S. Menorias
logo: logo.png

execute:
  execute_notebooks: auto

repository:
  url: https://github.com/NicoleMenorias/deeplearning-portfolio
  branch: main
  path_to_book: .   # book is at repo root

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
